import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/navbar";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Aurelium | Home",
  description: "Generated by create next app",
  icons : {
    icon : '/logo.png'
  }

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
};